### ISSUE TITLE
Issue on page /Userdocs/SingleNeuronExample.html

### ISSUE THREAD

**Issue by moscraciunxxx** [NeuroML/Documentation#94] opened 2021-09-10 00:30 UTC
Hello,
I cannot see the "rocket " icon on the right top corner of the page in order to run the code on Jupyter.

Could you please suggest a solution to this ? 
[New Document Microsoft Word.docx](https://github.com/NeuroML/Documentation/files/7140410/New.Document.Microsoft.Word.docx)

**Comment by sanjayankur31** [comment] 2021-09-10 07:46
Hi @moscraciunxxx , thanks for the issue report.

Can you confirm what the URL of the page is please?

The static version that cannot be run with lots of information is this:
https://docs.neuroml.org/Userdocs/SingleNeuronExample.html

and the interactive notebook that you can run is the next page:
https://docs.neuroml.org/Userdocs/NML2_examples/SingleNeuron.html

PS: you can upload images to GitHub issues, no need to put them in a doc file first

**Comment by moscraciunxxx** [comment] 2021-09-10 11:08
Hi Ankur,


Thank you for the help.

Kind regards. 



Sent from Mail.ru app for iOS


Friday, 10 September 2021, 10:46 +0300 from ***@***.***  ***@***.***>:

**Comment by sanjayankur31** [comment] 2021-09-10 11:39
No worries, I assume that means the issue is solved. Please re-open or open new issues if required. Closing this one now.

**Closed by sanjayankur31** 2021-09-10 11:39 UTC
Labels: T: bug

**Comment by moscraciunxxx** [comment] 2021-09-11 23:05
Hi Ankur,
 
 
I do have a question in regards to how can I connect the NeuroML toolbox to Matlab?
 
I have tried to follow up the instructions from the webpage but I guess I am missing something here.
Could you please help me in this matter ?
 
 
Kind regards, Vitalie 
  
>Пятница, 10 сентября 2021, 10:46 +03:00 от Ankur Sinha ***@***.***>:
> 
> 
>Hi  @moscraciunxxx , thanks for the issue report.
>Can you confirm what the URL of the page is please?
>The static version that cannot be run with lots of information is this:
>https://docs.neuroml.org/Userdocs/SingleNeuronExample.html
>and the interactive notebook that you can run is the next page:
>https://docs.neuroml.org/Userdocs/NML2_examples/SingleNeuron.html
>PS: you can upload images to GitHub issues, no need to put them in a doc file first
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>Triage notifications on the go with GitHub Mobile for  iOS or  Android .  
 
 
--
Cervinschi Vitalie

**Comment by sanjayankur31** [comment] 2021-09-12 09:35
I don't have a Matlab installation, so this will be hard to verify. What errors are you seeing? 

I also see that the instructions are for Matlab 2016, so it's possible that something has changed in recent releases. I'll look around to see if there's someone who can test the steps for us.

If at all possible, I'd suggest using the Python tools. Those are what we are focussed on, and they contain lots of extra utilities etc. over what would be available in the Matlab.

**Comment by moscraciunxxx** [comment] 2021-09-12 18:13
Thank you for your reply.
 
I will try and use Python tools as you mentioned, and see if I can get the workaround for this matter.
 
Also, if you find someone that managed to solve this, please do let me know.
 
The problem on my end is somehow related to installing the toolbox on my machine, other than that I have tried to follow all the steps from the instructions. 
 
Kind regards, Vitalie 
  
>Воскресенье, 12 сентября 2021, 12:35 +03:00 от Ankur Sinha ***@***.***>:
> 
> 
>I don't have a Matlab installation, so this will be hard to verify. What errors are you seeing?
>I also see that the instructions are for Matlab 2016, so it's possible that something has changed in recent releases. I'll look around to see if there's someone who can test the steps for us.
>If at all possible, I'd suggest using the Python tools. Those are what we are focussed on, and they contain lots of extra utilities etc. over what would be available in the Matlab.
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>Triage notifications on the go with GitHub Mobile for  iOS or  Android .  
 
 
--
Cervinschi Vitalie

**Comment by moscraciunxxx** [comment] 2021-09-14 00:28
Hi Ankur,
 
 
I am in need for your help again ( I do apologize for bothering you).
 
I have installed Anaconda on my machine, and I am trying to use the scripts from the NeuroML webpage to simulate the scripts and try it on my own, and the IDE that I use is Spyder. Now, for some reasons, it cannot recognize the libraries that Anaconda has, and also I have followed the steps on the NeuroML webpage on «how to set up your environment», but I guess there is something I am not doing correctly. I have tried the Jupyter notebook as well, but still does not want to import the libraries.
 
Could you please let me know what I am missing ?
 
Kind regards, VItalie 
  
>Воскресенье, 12 сентября 2021, 12:35 +03:00 от Ankur Sinha ***@***.***>:
> 
> 
>I don't have a Matlab installation, so this will be hard to verify. What errors are you seeing?
>I also see that the instructions are for Matlab 2016, so it's possible that something has changed in recent releases. I'll look around to see if there's someone who can test the steps for us.
>If at all possible, I'd suggest using the Python tools. Those are what we are focussed on, and they contain lots of extra utilities etc. over what would be available in the Matlab.
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>Triage notifications on the go with GitHub Mobile for  iOS or  Android .  
 
 

Cervinschi Vitalie,
MSc graduate, Goldsmiths — University of London, UK

**Comment by sanjayankur31** [comment] 2021-09-15 10:17
Could you confirm that you are able to access the neuroml libraries on the command line in your anaconda environment? if that works, then you probably just need to run spyder in this anaconda environment. By default, it'll run with the system paths etc., so you need to activate the anaconda environment and then run spyder from the environment for spyder to pick up the new paths.

What operating system are you on, by the way?

A web search brought me to this, which looks correct:

https://medium.com/@apremgeorge/using-conda-python-environments-with-spyder-ide-and-jupyter-notebooks-in-windows-4e0a905aaac5

It tells you how to set the PYTHONPATH in Spyder.

Please feel free to drop by on the Gitter chat channel (you login using GitHub there). I'll be on it from 0900 - 1700 London time on all weekdays.

https://gitter.im/NeuroML/community

**Comment by moscraciunxxx** [comment] 2021-09-15 17:21
Hi Ankur,
 
 
Thank you for your reply.
I think this was the issue, I had to add the PYTHONPATH correctly but for some reason it did not work for me.
 
Let me check the link that you have sent and get back to you in case of need.
 
I am using a Windows 10 OS. 
 
Many thanks, Vitalie 
  
>Среда, 15 сентября 2021, 13:17 +03:00 от Ankur Sinha ***@***.***>:
> 
> 
>Could you confirm that you are able to access the neuroml libraries on the command line in your anaconda environment? if that works, then you probably just need to run spyder in this anaconda environment. By default, it'll run with the system paths etc., so you need to activate the anaconda environment and then run spyder from the environment for spyder to pick up the new paths.
>What operating system are you on, by the way?
>A web search brought me to this, which looks correct:
***@***.***/using-conda-python-environments-with-spyder-ide-and-jupyter-notebooks-in-windows-4e0a905aaac5
>It tells you how to set the PYTHONPATH in Spyder.
>Please feel free to drop by on the Gitter chat channel (you login using GitHub there). I'll be on it from 0900 - 1700 London time on all weekdays.
>https://gitter.im/NeuroML/community
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>Triage notifications on the go with GitHub Mobile for  iOS or  Android .  
 
 

Cervinschi Vitalie,
MSc graduate, Goldsmiths — University of London, UK

**Comment by sanjayankur31** [comment] 2021-09-16 08:09
Great, please do let me know if you run into any issues. Cheers,

**Comment by moscraciunxxx** [comment] 2021-09-16 09:02
Hi Ankur,
 
 
I have followed up with the steps from the link, but I get an error at the end of it, and when I try to make use of the new environment, I get the error of Kernel not being recognized at all.
 
I think I need to look more into this online, I am really confused right now.
 
 
Many thanks, Vitalie 
  
>Четверг, 16 сентября 2021, 11:10 +03:00 от Ankur Sinha ***@***.***>:
> 
> 
>Great, please do let me know if you run into any issues. Cheers,
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>Triage notifications on the go with GitHub Mobile for  iOS or  Android .  
 
 

Cervinschi Vitalie,
MSc graduate, Goldsmiths — University of London, UK

**Comment by sanjayankur31** [comment] 2021-09-16 09:12
Ah, hrm, that sounds something generally conda related I'm afraid.

In general, I run bits using python virtual environments, which should be very similar to conda environments:

```
python3 -m venv ./venv
source .venv/bin/activate
pip install <packages>
# work 
```

and that tends to work. I guess I don't use spyder and so on so I'm not sure how one gets them to use virtual environments.  This is Windows too, which is a little different to how we work on Linux/Mac.

I guess it'll be best to start with the terminal (without spyder) to see if things work in a normal python interpreter. Once you have that set up, spyder needs to be configured to use the environment.

**Comment by moscraciunxxx** [comment] 2021-09-16 09:15
Yes, I think there lies the issue.
 
Let me try and see what can I get on the web, and if it is still not working properly, I’ll try some other IDEs.
 
Many thanks, VItalie 
  
>Четверг, 16 сентября 2021, 12:12 +03:00 от Ankur Sinha ***@***.***>:
> 
> 
>Ah, hrm, that sounds something generally conda related I'm afraid.
>In general, I run bits using python virtual environments, which should be very similar to conda environments:
>python3 -m venv ./venv
>source .venv/bin/activate
>pip install <packages>
># work 
>
>and that tends to work. I guess I don't use spyder and so on so I'm not sure how one gets them to use virtual environments. This is Windows too, which is a little different to how we work on Linux/Mac.
>I guess it'll be best to start with the terminal (without spyder) to see if things work in a normal python interpreter. Once you have that set up, spyder needs to be configured to use the environment.
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>Triage notifications on the go with GitHub Mobile for  iOS or  Android .  
 
 

Cervinschi Vitalie,
MSc graduate, Goldsmiths — University of London, UK

**Comment by moscraciunxxx** [comment] 2021-09-16 09:31
I have managed to make the environment recognize my modules, the ones that anaconda has installed, but the only thing right now, is to connect the neuroML module to it, and I guess this will be the trickiest part.

  
>Четверг, 16 сентября 2021, 12:12 +03:00 от Ankur Sinha ***@***.***>:
> 
> 
>Ah, hrm, that sounds something generally conda related I'm afraid.
>In general, I run bits using python virtual environments, which should be very similar to conda environments:
>python3 -m venv ./venv
>source .venv/bin/activate
>pip install <packages>
># work 
>
>and that tends to work. I guess I don't use spyder and so on so I'm not sure how one gets them to use virtual environments. This is Windows too, which is a little different to how we work on Linux/Mac.
>I guess it'll be best to start with the terminal (without spyder) to see if things work in a normal python interpreter. Once you have that set up, spyder needs to be configured to use the environment.
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>Triage notifications on the go with GitHub Mobile for  iOS or  Android .  
 
 

Cervinschi Vitalie,
MSc graduate, Goldsmiths — University of London, UK

**Comment by sanjayankur31** [comment] 2021-09-16 09:44
If the modules from the environment are accessible, you just need to install the neuroml bits into this environment. `pip install pyneuroml` when the environment is activated should pretty much do it.

**Comment by moscraciunxxx** [comment] 2021-09-16 09:50
Done.  It seems I have managed to make it work. I will try some other examples from the neuroML websites, and see if I get any errors regarding other scripts.
 
Many thanks for your responses.
 
Kind regards, Vitalie 
  
>Четверг, 16 сентября 2021, 12:45 +03:00 от Ankur Sinha ***@***.***>:
> 
> 
>If the modules from the environment are accessible, you just need to install the neuroml bits into this environment. pip install pyneuroml when the environment is activated should pretty much do it.
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>Triage notifications on the go with GitHub Mobile for  iOS or  Android .  
 
 

Cervinschi Vitalie,
MSc graduate, Goldsmiths — University of London, UK

**Comment by sanjayankur31** [comment] 2021-09-16 09:55
awesome, that's good to hear.
